### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by alonsotagle** [fastly/sigsci-module-python#3]
The `pip3 install sigscimodule-1.4.1.tar.gz` command fails because there is no setup.py or pyproject.toml files in the root of the repo

Steps to reproduce:
```bash
git clone git@github.com:fastly/sigsci-module-python.git
cd sigsci-module-python
make build
pip3 install sigscimodule-1.4.1.tar.gz
```

Result:
```bash
Processing ./sigscimodule-1.4.1.tar.gz
ERROR: file:///sigscimodule-1.4.1.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by vcarvajal-sigsci** [comment]
Give the [latest](https://github.com/fastly/sigsci-module-python/commit/317e2ea7ebfa478118f6e93adc8a7c131dcc485c) a try

**Comment by alonsotagle** [comment]
I followed the steps but it still doesn't work

**Comment by vcarvajal-sigsci** [comment]
can you unpackage the .tar.gz and see if the setup.py is missing?

**Comment by alonsotagle** [comment]
setup.py exists in the .tar.gz
